[2022-09-27 06:09:00,052] {processor.py:163} INFO - Started process (PID=43) to work on /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:09:00,055] {processor.py:620} INFO - Processing file /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-09-27 06:09:00,056] {logging_mixin.py:109} INFO - [2022-09-27 06:09:00,056] {dagbag.py:500} INFO - Filling up the DagBag from /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:09:00,071] {logging_mixin.py:109} INFO - [2022-09-27 06:09:00,069] {dagbag.py:334} ERROR - Failed to import: /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dag.py", line 2970, in factory
    f(**f_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-09-27 06:09:00,088] {processor.py:634} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:09:00,104] {processor.py:171} INFO - Processing /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.057 seconds
[2022-09-27 06:09:40,152] {processor.py:163} INFO - Started process (PID=77) to work on /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:09:40,161] {processor.py:620} INFO - Processing file /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-09-27 06:09:40,162] {logging_mixin.py:109} INFO - [2022-09-27 06:09:40,162] {dagbag.py:500} INFO - Filling up the DagBag from /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:09:40,169] {logging_mixin.py:109} INFO - [2022-09-27 06:09:40,168] {dagbag.py:334} ERROR - Failed to import: /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dag.py", line 2970, in factory
    f(**f_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-09-27 06:09:40,181] {processor.py:634} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:09:40,196] {processor.py:171} INFO - Processing /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.047 seconds
[2022-09-27 06:10:19,823] {processor.py:163} INFO - Started process (PID=133) to work on /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:10:19,824] {processor.py:620} INFO - Processing file /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-09-27 06:10:19,826] {logging_mixin.py:109} INFO - [2022-09-27 06:10:19,826] {dagbag.py:500} INFO - Filling up the DagBag from /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:10:19,834] {logging_mixin.py:109} INFO - [2022-09-27 06:10:19,832] {dagbag.py:334} ERROR - Failed to import: /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dag.py", line 2970, in factory
    f(**f_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-09-27 06:10:19,844] {processor.py:634} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:10:19,875] {processor.py:171} INFO - Processing /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.054 seconds
[2022-09-27 06:10:55,017] {processor.py:163} INFO - Started process (PID=162) to work on /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:10:55,019] {processor.py:620} INFO - Processing file /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-09-27 06:10:55,020] {logging_mixin.py:109} INFO - [2022-09-27 06:10:55,020] {dagbag.py:500} INFO - Filling up the DagBag from /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:10:55,032] {logging_mixin.py:109} INFO - [2022-09-27 06:10:55,031] {dagbag.py:334} ERROR - Failed to import: /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dag.py", line 2970, in factory
    f(**f_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-09-27 06:10:55,046] {processor.py:634} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:10:55,064] {processor.py:171} INFO - Processing /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.054 seconds
[2022-09-27 06:11:28,034] {processor.py:163} INFO - Started process (PID=190) to work on /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:11:28,050] {processor.py:620} INFO - Processing file /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-09-27 06:11:28,069] {logging_mixin.py:109} INFO - [2022-09-27 06:11:28,069] {dagbag.py:500} INFO - Filling up the DagBag from /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:11:28,093] {logging_mixin.py:109} INFO - [2022-09-27 06:11:28,092] {dagbag.py:334} ERROR - Failed to import: /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dag.py", line 2970, in factory
    f(**f_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-09-27 06:11:28,111] {processor.py:634} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:11:28,132] {processor.py:171} INFO - Processing /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.100 seconds
[2022-09-27 06:12:00,560] {processor.py:163} INFO - Started process (PID=218) to work on /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:12:00,562] {processor.py:620} INFO - Processing file /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-09-27 06:12:00,564] {logging_mixin.py:109} INFO - [2022-09-27 06:12:00,564] {dagbag.py:500} INFO - Filling up the DagBag from /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:12:00,576] {logging_mixin.py:109} INFO - [2022-09-27 06:12:00,574] {dagbag.py:334} ERROR - Failed to import: /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dag.py", line 2970, in factory
    f(**f_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-09-27 06:12:00,592] {processor.py:634} WARNING - No viable dags retrieved from /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-09-27 06:12:00,609] {processor.py:171} INFO - Processing /usr/local/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.053 seconds
