[2022-09-27 08:28:19,242] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: recruitment-airflow.crawling manual__2022-09-27T08:28:16.695236+00:00 [queued]>
[2022-09-27 08:28:19,265] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: recruitment-airflow.crawling manual__2022-09-27T08:28:16.695236+00:00 [queued]>
[2022-09-27 08:28:19,266] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-09-27 08:28:19,267] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-09-27 08:28:19,268] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-09-27 08:28:19,327] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): crawling> on 2022-09-27 08:28:16.695236+00:00
[2022-09-27 08:28:19,330] {standard_task_runner.py:52} INFO - Started process 41486 to run task
[2022-09-27 08:28:19,332] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'recruitment-airflow', 'crawling', 'manual__2022-09-27T08:28:16.695236+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/recruitment_pipeline.py', '--cfg-path', '/tmp/tmpse_oij90', '--error-file', '/tmp/tmpy81c18yv']
[2022-09-27 08:28:19,334] {standard_task_runner.py:77} INFO - Job 33: Subtask crawling
[2022-09-27 08:28:19,436] {logging_mixin.py:109} INFO - Running <TaskInstance: recruitment-airflow.crawling manual__2022-09-27T08:28:16.695236+00:00 [running]> on host pipeline
[2022-09-27 08:28:19,502] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/xcom.py:323 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-09-27 08:28:19,525] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/renderedtifields.py:126 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-09-27 08:28:19,566] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/renderedtifields.py:162 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2022-09-27 08:28:19,571] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/renderedtifields.py:159 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-09-27 08:28:19,601] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=recruitment-airflow
AIRFLOW_CTX_TASK_ID=crawling
AIRFLOW_CTX_EXECUTION_DATE=2022-09-27T08:28:16.695236+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-27T08:28:16.695236+00:00
[2022-09-27 08:28:19,603] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-27 08:28:19,605] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/pipeline/script/crawlingToMongo.py']
[2022-09-27 08:28:19,611] {subprocess.py:85} INFO - Output:
[2022-09-27 08:28:23,023] {subprocess.py:89} INFO - /opt/pipeline/script/crawlingToMongo.py:20: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
[2022-09-27 08:28:23,024] {subprocess.py:89} INFO -   driver = webdriver.Chrome(executable_path=path, chrome_options=chrome_options)
[2022-09-27 08:28:23,026] {subprocess.py:89} INFO - /opt/pipeline/script/crawlingToMongo.py:20: DeprecationWarning: use options instead of chrome_options
[2022-09-27 08:28:23,027] {subprocess.py:89} INFO -   driver = webdriver.Chrome(executable_path=path, chrome_options=chrome_options)
[2022-09-27 08:28:23,028] {subprocess.py:89} INFO - <configparser.ConfigParser object at 0xffff98a9c9d0>
[2022-09-27 08:28:23,029] {subprocess.py:89} INFO - Traceback (most recent call last):
[2022-09-27 08:28:23,030] {subprocess.py:89} INFO -   File "/opt/pipeline/script/crawlingToMongo.py", line 27, in <module>
[2022-09-27 08:28:23,031] {subprocess.py:89} INFO -     host = parser["mongodb_credentials"]["host"]
[2022-09-27 08:28:23,032] {subprocess.py:89} INFO -   File "/usr/local/lib/python3.8/configparser.py", line 960, in __getitem__
[2022-09-27 08:28:23,034] {subprocess.py:89} INFO -     raise KeyError(key)
[2022-09-27 08:28:23,036] {subprocess.py:89} INFO - KeyError: 'mongodb_credentials'
[2022-09-27 08:28:23,124] {subprocess.py:93} INFO - Command exited with return code 1
[2022-09-27 08:28:23,135] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-09-27 08:28:23,139] {taskinstance.py:1270} INFO - Marking task as FAILED. dag_id=recruitment-airflow, task_id=crawling, execution_date=20220927T082816, start_date=20220927T082819, end_date=20220927T082823
[2022-09-27 08:28:23,209] {standard_task_runner.py:88} ERROR - Failed to execute job 33 for task crawling
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-09-27 08:28:23,245] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-27 08:28:23,374] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-27 08:28:23,376] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/dag.py:1069 SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
[2022-09-27 08:28:23,377] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/dag.py:1069 SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)
